model_path: "model.onnx"
embodiment: "gpr"
resources_dir: "keval/resources"

eval_suites:
  locomotion: false
  krec: false
  manipulation_mani_skill: false
  whole_body_control: false

eval_envs:
  locomotion:
    seed: 42
    eval_runs: 10
    sim_duration: 10
    record_video: false
  
    metrics:
      - episode_length
      - episode_reward
      - position_error
      - tracking_error
      - contact_forces

  krec:
    metrics:
      - l2_error
      - mse

  manipulation_mani_skill:
    max_steps: 1000
    seed: 42
    eval_runs: 10
    sim_duration: 20
    record_video: false

    metrics:
      - l2_error
      - mse

logging:
  log_dir: "logs"
  save_video: true

robot:
  joints:
    - "L_hip_y"
    - "L_hip_z"
    - "L_hip_x"
    - "L_knee"
    - "L_ankle_y"
    - "R_hip_y"
    - "R_hip_z"
    - "R_hip_x"
    - "R_knee"
    - "R_ankle_y"

io_schema:
  input:
    - value_name: "joint_positions"
      type: "joint_positions"
      schema:
        joint_names: ${robot.joints}
        unit: "radians"
    
    - value_name: "joint_velocities"
      type: "joint_velocities" 
      schema:
        joint_names: ${robot.joints}
        unit: "radians_per_second"
    
    - value_name: "vector_command"
      type: "vector_command"
      schema:
        dimensions: 3
    
    - value_name: "imu"
      type: "imu"
      schema:
        use_accelerometer: true
        use_gyroscope: true
        use_magnetometer: true
    
    - value_name: "timestamp"
      type: "timestamp"
      schema:
        start_seconds: 0
        start_nanos: 0
    
    - value_name: "camera_frame_left"
      type: "camera_frame"
      schema:
        width: 640
        height: 480
        channels: 3
    
    - value_name: "camera_frame_right"
      type: "camera_frame"
      schema:
        width: 640
        height: 480
        channels: 3

  output:
    - value_name: "joint_torques"
      type: "joint_torques"
      schema:
        joint_names: ${robot.joints}
        unit: "newton_meters"
