model_path: "gpr_walking.onnx"
embodiment: "gpr"

eval_suites:
  locomotion: true

eval_envs:
  locomotion:
    seed: 42
    eval_runs: 2
    sim_duration: .2
    record_video: true

    metrics:
      - success_rate
      - mean_episode_length
      - mean_episode_reward
      - mean_episode_cost
      - tracking_error
      - collision_cost

logging:
  log_dir: "logs"
  save_video: true
